### ISSUE TITLE
Node 5.5.0 is unable to install grunt-springroll (files missing)

### ISSUE THREAD

**Issue by trjh2k2** [SpringRoll/grunt-springroll#2]
Attempting to install grunt-springroll ("npm install grunt-springroll") doesn't appear to download/install all of the files in the package, if you're using the latest versions of Node and npm.  Using the LTS version of Node and npm works correctly though (Node 4.2.6 and npm 2.14.12).

**Comment by chipbell4** [comment]
Okay, this should now be resolved with https://github.com/SpringRoll/grunt-springroll/pull/6 and is available in [grunt-springroll 0.7.11](https://www.npmjs.com/package/grunt-springroll). Let me know if you're still running into this issue
