### ISSUE TITLE
Error with `grunt build-debug` on SpringRoll project...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/grunt-springroll#5]
I haven't run into this kind of issue with grunt before, so any help would be appreciated. Running `grunt build-debug` results in the following error:

    >> Local Npm module "grunt-bower-task" not found. Is it installed?
    >> Local Npm module "grunt-concat-json" not found. Is it installed?
    >> Local Npm module "grunt-contrib-clean" not found. Is it installed?
    >> Local Npm module "grunt-contrib-concat" not found. Is it installed?
    >> Local Npm module "grunt-contrib-connect" not found. Is it installed?
    >> Local Npm module "grunt-contrib-copy" not found. Is it installed?
    >> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
    >> Local Npm module "grunt-contrib-less" not found. Is it installed?
    >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
    >> Local Npm module "grunt-contrib-watch" not found. Is it installed?
    >> Local Npm module "grunt-newer" not found. Is it installed?
    >> Local Npm module "grunt-simple-version" not found. Is it installed?
    >> Local Npm module "grunt-springroll-helper" not found. Is it installed?
    >> Local Npm module "grunt-text-replace" not found. Is it installed?
    >> Tasks directory "tasks" not found.
    >> Local Npm module "grunt-contrib-nodeunit" not found. Is it installed?
    Warning: Task "concat:main" not found. Use --force to continue.
    
    Aborted due to warnings.

I tried deleting the "node_modules" folder and running `npm install` but I still get the same list of missing modules. So then I tried another project that was working and ran `grunt build-debug`: it worked correctly. Then I removed the "node_modules" folder from this working project, ran `npm install` and then ran `grunt build-debug` and got the same list of issues shown above. So I was able to replicate the issue by running `npm install`.

Looking at a working projects folder, it appears to have a very "nested" folder structure where more "node_modules" folders are nested with each dependency, whereas the broken project has a flattened folder structure with many dependencies in the root "node_modules" folder.

Could I be running the wrong version of node, npm, or some other dependency or might anyone have other recommendations on how to fix my corrupted projects? I suppose I can copy/paste the node_modules folder of another working project, but that's not much of a long-term solution.

    node --version
    v4.2.4
    
    npm --version
    4.0.5
    
    grunt --version
    grunt-cli v0.1.13
    grunt v1.0.1

**Comment by andrewstart** [comment]
Yeah, a dependency of a dependency doesn't handle the flattened installs of NPM 3+. I've made [a PR](https://github.com/firstandthird/load-grunt-config/pull/167) to our dependency to update their dependency to fix that, but I don't know if that'll happen soon.

**Comment by probityrules** [comment]
Ah, gotcha, I wasn't aware of the difference in installation between npm versions. This makes a bit more sense now.

**Comment by chipbell4** [comment]
Okay, this should now be resolved with https://github.com/SpringRoll/grunt-springroll/pull/6 and is available in [grunt-springroll 0.7.11](https://www.npmjs.com/package/grunt-springroll). Let me know if you're still running into this issue
